In [1]:
import os
import numpy as np
import torch
import torch.optim as optim
import torch.distributions as D
from tqdm import tqdm, trange
from src.svgd import SVGD
from src.gsvgd import FullGSVGDBatch
from src.kernel import RBF, BatchRBF
from src.utils import plot_particles
from src.Tmy_svgd import etmySVGD
from src.manifold import Grassmann
from src.s_svgd import SlicedSVGD
from src.MP_SVGD import mp_shape_SVGD
import matplotlib.pyplot as plt
from src.rand_mysvgd import mySVGD
from scipy.stats import energy_distance
import pickle
import argparse
import time
import torch.autograd as autograd

/home/zhoujk/anaconda3/envs/AG/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
parser = argparse.ArgumentParser(description='Running xshaped experiment.')
parser.add_argument('--dim', type=int,default=10000, help='dimension')
parser.add_argument('--effdim', type=int, default=-1, help='dimension')
parser.add_argument('--lr', type=float,default=0.01, help='learning rate')
parser.add_argument('--lr_g', type=float, default=0.1, help='learning rate for g')
parser.add_argument('--delta', type=float,default=0.01, help='stepsize for projections')
parser.add_argument('--T', type=float, default=1e-4, help='noise multiplier for projections')
parser.add_argument('--nparticles', type=int,default=100, help='no. of particles')
parser.add_argument('--epochs', type=int, default=20,help='no. of epochs')
parser.add_argument('--nmix', type=int, default=2, help='no. of modes')
parser.add_argument('--metric', type=str, default="energy", help='distance metric')
parser.add_argument('--noise', type=str, default="True", help='whether to add noise')
parser.add_argument('--kernel', type=str, default="rbf", help='kernel')
parser.add_argument('--gpu', type=int, default=7, help='gpu')
parser.add_argument('--seed', type=int, default=0, help='random seed') 
parser.add_argument('--suffix', type=str, default="", help='suffix for res folder')
parser.add_argument('--m', type=int, help='no. of projections')
parser.add_argument('--save_every', type=int, default=200, help='step intervals to save particles')
parser.add_argument('--method', type=str, default="all", help='which method to use')


args = parser.parse_args([])
device = torch.device(f'cuda:{args.gpu}' if args.gpu != -1 else 'cpu')
dim = args.dim
lr = args.lr
delta = args.delta
T = args.T
nparticles = args.nparticles
epochs = args.epochs
seed = args.seed
eff_dims = 3
nmix = args.nmix
add_noise = True if args.noise == "True" else False
radius = 5
save_every = args.save_every
print(f"Running for dim: {dim}, lr: {lr}, nparticles: {nparticles}")

Running for dim: 10000, lr: 0.01, nparticles: 100


In [3]:
def mix_gauss_experiment(mixture_dist, means, correlation):
    '''Mixture of Multivariate gaussian with cov matrices being the identity.
    Args:
        mixture_dist: torch.distributions.Categorical-like instance for the 
            probability of each component in the mixture.
        means: Tensor of shape (nmix, d), where nmix is the number of components 
            and d is the dimension of each component.
        correlation: Float between 0 and 1 for the magnitude of correlation between
            the first two dims.
    '''
    nmix, dim = means.shape
    nmix = nmix + 1
    
    # create multibatch multivariate Gaussian
    cov1 = torch.eye(dim, device=device)
    cov1[:2, :2] = torch.Tensor([[2, 0.01],[0.01, 2]])
   
    
    #cov1[dim-2:, dim-2:] = torch.Tensor([[1, correlation], [correlation, 1]])
    cov2 = torch.eye(dim, device=device)
    cov2[:2, :2] = torch.Tensor([[2, 0], [0, 2]])
    #cov2[dim-2:, dim-2:] = torch.Tensor([[1, 0], [0, 1]])
   
    mix_cov = torch.stack((cov1, cov2))
   
    comp = D.MultivariateNormal(means.to(device), mix_cov)

    distribution = D.mixture_same_family.MixtureSameFamily(mixture_dist, comp)   
    return(distribution)

In [4]:
mix_means_x = torch.zeros((2, 100), device=device)
mix_means_x[:, :2] = 0

distribution = mix_gauss_experiment(
    mixture_dist=D.Categorical(torch.ones(mix_means_x.shape[0], device=device)),
    means=mix_means_x,
    correlation=0.01
)

In [5]:
x_target = distribution.sample((nparticles, ))
        # sample from variational density
torch.manual_seed(235)
x_init = 2 + np.sqrt(2) * torch.randn(nparticles, *distribution.event_shape, device=device)
Kernel = RBF
kernel = Kernel(method="med_heuristic")

In [6]:
def score(X):
    X_cp = X.detach().requires_grad_(True)
    log_prob = distribution.log_prob(X_cp)
    score_func = autograd.grad(log_prob.sum(), X_cp, retain_graph=False)[0]
            
    score_func1 = score_func.clone().detach()
    return score_func1

def svgd_kernel(theta_ab):
        """gaussian rbf kernel function"""

        X_cp = theta_ab.clone().requires_grad_()
       
        Y = theta_ab.clone()
        with torch.no_grad():
            kernel.bandwidth(theta_ab, theta_ab)
        K_XX = kernel(X_cp, Y)
        
        grad_K = -autograd.grad(K_XX.sum(), X_cp, retain_graph=False)[0] 
        
        
        

        return K_XX, grad_K

In [7]:

    
def del_tensor_ele( arr, index):
    index = index.to(torch.int)

    # print(index)
    arr1 = arr[0:index]
    arr2 = arr[index+1:]
    return torch.cat((arr1, arr2), dim=0)

def divide( theta,  k):
    theta1 = theta.clone()
    theta1 = theta1 - torch.mean(theta1, 0)
    list = torch.norm(theta1, p=2, dim=0)
    max_list = torch.topk(list, k=k, dim = 0, largest=True, sorted=False)
    support = max_list.indices
    print(support)
    min_list = torch.topk(list, k=theta.shape[1]-k, dim = 0, largest=False, sorted=False)
    blanket = min_list.indices
    

    return blanket, support




def svgd_kernel( theta_ab):
    """gaussian rbf kernel function"""

    X_cp = theta_ab.clone().requires_grad_()
    
    Y = theta_ab.clone()
    
    kernel.bandwidth(theta_ab, theta_ab)
    K_XX = kernel(X_cp, Y)
    
    grad_K = -autograd.grad(K_XX.sum(), X_cp)[0] 
    
    
    

    return K_XX, grad_K







def power(theta, part, s, lnpgrad):
    theta_ab1 = torch.cat([theta[:,part],theta[:,s].view(theta.shape[0], 1)], 1)
    
            
            
    lnpgrad_j1 = lnpgrad[:,s]
            # calculating the kernel matrix
    kxy1, repulsion1 = svgd_kernel(theta_ab1) 
    
    
    attraction1 = torch.matmul(kxy1, lnpgrad_j1) 
    return  attraction1 + repulsion1[:,-1]

def update_blanket( theta, lnpgrad, k, lr ):
    
            
    blanket , support = divide(theta, k)
    
                    
            
    theta_ab = torch.cat([theta[:,blanket],theta[:,support]], 1)
            
    lnpgrad_blanket = lnpgrad[:,blanket]
                # calculating the kernel matrix
    kxy, repulsion = svgd_kernel(theta_ab) 
        
    
    attraction = torch.matmul(kxy, lnpgrad_blanket) 
                

    theta[:,blanket] = theta[:,blanket]  + 0.01*lr*(attraction + repulsion[:, 0:blanket.size(0)]) / theta_ab.size(0)

    return theta, blanket, support


def update_dim(score, theta, k, lr):

    lnpgrad = score(theta)
            
    theta, blanket, support = update_blanket(theta,  lnpgrad, k, lr )

        
    grad1_theta = theta.clone().detach()
    grad2_theta = theta.clone().detach()


    iterator_dim = range(theta.shape[1])
    s = -1

    for j in iterator_dim:
        s = s + 1
        
        if s in blanket:
            a = torch.where(blanket == s)[0]

            blanket = del_tensor_ele(blanket, a)
        if s in support:
            a = torch.where(support == s)[0]

            support = del_tensor_ele(support, a)

    #### STEP2 blanket_to_d
        
        grad1 = power(grad1_theta, blanket, s, lnpgrad)

    ### STEP3 SUPPORT_to_d
        grad2 = power(theta, support, s, lnpgrad)
        


    
    
        vec1 = 0.02*lr*grad1 / (blanket.shape[0] + 1)
        vec2 = lr*grad2 / (support.shape[0] + 1)
    
        grad1_theta[:,s] =  vec1 
        
    
        grad2_theta[:,s] = vec2 
        
    
    


    return grad1_theta, grad2_theta



    
    






def update( x0,score, n_iter = 1000, k = 8, lr=0.001):

    
    theta = x0.clone().detach()
    


    iterator = tqdm(range(n_iter)) 
        
    
    vector1 = torch.zeros_like(theta).detach()

    for  i in iterator:
        a, b = update_dim(score, theta, k, lr)
        opt =  optim.Adam([x0], lr=lr)
        opt.zero_grad()
        x0.grad = a
        opt.step()
        opt.zero_grad()
        x0.grad = b
        opt.step()
    return theta

In [8]:
x0 = x_init.clone().detach().to(device)
update( x0,score, n_iter = 10000, k = 2, lr=0.001)
    

  0%|          | 0/10000 [00:00<?, ?it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 1/10000 [00:00<1:28:08,  1.89it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 2/10000 [00:00<1:18:47,  2.12it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 3/10000 [00:01<1:15:45,  2.20it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 4/10000 [00:01<1:13:51,  2.26it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 5/10000 [00:02<1:08:14,  2.44it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 6/10000 [00:02<1:04:47,  2.57it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 7/10000 [00:02<1:02:14,  2.68it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 8/10000 [00:03<1:00:47,  2.74it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 9/10000 [00:03<59:28,  2.80it/s]  

tensor([75, 67], device='cuda:7')


  0%|          | 10/10000 [00:03<58:57,  2.82it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 11/10000 [00:04<59:01,  2.82it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 12/10000 [00:04<58:23,  2.85it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 13/10000 [00:04<57:47,  2.88it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 14/10000 [00:05<57:31,  2.89it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 15/10000 [00:05<57:21,  2.90it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 16/10000 [00:05<57:21,  2.90it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 17/10000 [00:06<57:44,  2.88it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 18/10000 [00:06<57:34,  2.89it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 19/10000 [00:07<57:36,  2.89it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 20/10000 [00:07<57:25,  2.90it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 21/10000 [00:07<57:18,  2.90it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 22/10000 [00:08<57:15,  2.90it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 23/10000 [00:08<57:20,  2.90it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 24/10000 [00:08<57:37,  2.89it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 25/10000 [00:09<57:54,  2.87it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 26/10000 [00:09<57:48,  2.88it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 27/10000 [00:09<57:42,  2.88it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 28/10000 [00:10<57:59,  2.87it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 29/10000 [00:10<57:51,  2.87it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 30/10000 [00:10<57:55,  2.87it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 31/10000 [00:11<57:54,  2.87it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 32/10000 [00:11<57:41,  2.88it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 33/10000 [00:11<57:41,  2.88it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 34/10000 [00:12<57:45,  2.88it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 35/10000 [00:12<57:39,  2.88it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 36/10000 [00:12<57:53,  2.87it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 37/10000 [00:13<58:13,  2.85it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 38/10000 [00:13<58:12,  2.85it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 39/10000 [00:13<58:03,  2.86it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 40/10000 [00:14<57:57,  2.86it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 41/10000 [00:14<57:45,  2.87it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 42/10000 [00:15<57:54,  2.87it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 43/10000 [00:15<58:18,  2.85it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 44/10000 [00:15<58:14,  2.85it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 45/10000 [00:16<58:24,  2.84it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 46/10000 [00:16<58:04,  2.86it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 47/10000 [00:16<57:47,  2.87it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 48/10000 [00:17<57:43,  2.87it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 49/10000 [00:17<57:36,  2.88it/s]

tensor([75, 67], device='cuda:7')


  0%|          | 50/10000 [00:17<57:46,  2.87it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 51/10000 [00:18<57:42,  2.87it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 52/10000 [00:18<57:38,  2.88it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 53/10000 [00:18<57:30,  2.88it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 54/10000 [00:19<57:32,  2.88it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 55/10000 [00:19<57:27,  2.88it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 56/10000 [00:19<57:55,  2.86it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 57/10000 [00:20<57:49,  2.87it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 58/10000 [00:20<57:29,  2.88it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 59/10000 [00:20<57:21,  2.89it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 60/10000 [00:21<57:19,  2.89it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 61/10000 [00:21<57:23,  2.89it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 62/10000 [00:21<57:30,  2.88it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 63/10000 [00:22<57:41,  2.87it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 64/10000 [00:22<57:46,  2.87it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 65/10000 [00:23<57:38,  2.87it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 66/10000 [00:23<1:01:18,  2.70it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 67/10000 [00:23<1:06:54,  2.47it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 68/10000 [00:24<1:04:23,  2.57it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 69/10000 [00:24<1:02:14,  2.66it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 70/10000 [00:24<1:00:41,  2.73it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 71/10000 [00:25<59:35,  2.78it/s]  

tensor([75, 67], device='cuda:7')


  1%|          | 72/10000 [00:25<58:47,  2.81it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 73/10000 [00:26<58:24,  2.83it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 74/10000 [00:26<57:56,  2.86it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 75/10000 [00:26<57:57,  2.85it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 76/10000 [00:27<57:28,  2.88it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 77/10000 [00:27<57:03,  2.90it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 78/10000 [00:27<56:48,  2.91it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 79/10000 [00:28<56:51,  2.91it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 80/10000 [00:28<56:48,  2.91it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 81/10000 [00:28<56:58,  2.90it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 82/10000 [00:29<57:07,  2.89it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 83/10000 [00:29<57:07,  2.89it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 84/10000 [00:29<57:02,  2.90it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 85/10000 [00:30<57:00,  2.90it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 86/10000 [00:30<57:04,  2.89it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 87/10000 [00:30<56:51,  2.91it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 88/10000 [00:31<57:30,  2.87it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 89/10000 [00:31<57:16,  2.88it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 90/10000 [00:31<57:12,  2.89it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 91/10000 [00:32<57:11,  2.89it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 92/10000 [00:32<57:15,  2.88it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 93/10000 [00:32<56:59,  2.90it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 94/10000 [00:33<59:02,  2.80it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 95/10000 [00:33<1:07:01,  2.46it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 96/10000 [00:34<1:11:18,  2.31it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 97/10000 [00:34<1:07:35,  2.44it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 98/10000 [00:35<1:04:18,  2.57it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 99/10000 [00:35<1:02:01,  2.66it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 100/10000 [00:35<1:00:58,  2.71it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 101/10000 [00:36<59:46,  2.76it/s]  

tensor([75, 67], device='cuda:7')


  1%|          | 102/10000 [00:36<58:53,  2.80it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 103/10000 [00:36<58:14,  2.83it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 104/10000 [00:37<57:36,  2.86it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 105/10000 [00:37<57:29,  2.87it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 106/10000 [00:37<57:04,  2.89it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 107/10000 [00:38<57:02,  2.89it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 108/10000 [00:38<57:13,  2.88it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 109/10000 [00:38<56:53,  2.90it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 110/10000 [00:39<57:01,  2.89it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 111/10000 [00:39<56:51,  2.90it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 112/10000 [00:39<56:45,  2.90it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 113/10000 [00:40<57:13,  2.88it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 114/10000 [00:40<57:04,  2.89it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 115/10000 [00:40<56:42,  2.91it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 116/10000 [00:41<56:38,  2.91it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 117/10000 [00:41<56:36,  2.91it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 118/10000 [00:41<56:22,  2.92it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 119/10000 [00:42<56:43,  2.90it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 120/10000 [00:42<56:43,  2.90it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 121/10000 [00:42<56:35,  2.91it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 122/10000 [00:43<56:30,  2.91it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 123/10000 [00:43<56:24,  2.92it/s]

tensor([75, 67], device='cuda:7')


  1%|          | 124/10000 [00:43<56:32,  2.91it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 125/10000 [00:44<56:31,  2.91it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 126/10000 [00:44<56:53,  2.89it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 127/10000 [00:44<56:43,  2.90it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 128/10000 [00:45<57:00,  2.89it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 129/10000 [00:45<57:04,  2.88it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 130/10000 [00:46<57:23,  2.87it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 131/10000 [00:46<57:23,  2.87it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 132/10000 [00:46<58:39,  2.80it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 133/10000 [00:47<58:18,  2.82it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 134/10000 [00:47<57:33,  2.86it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 135/10000 [00:47<57:07,  2.88it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 136/10000 [00:48<56:52,  2.89it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 137/10000 [00:48<56:45,  2.90it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 138/10000 [00:48<56:35,  2.90it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 139/10000 [00:49<57:09,  2.88it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 140/10000 [00:49<57:10,  2.87it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 141/10000 [00:49<57:15,  2.87it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 142/10000 [00:50<57:21,  2.86it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 143/10000 [00:50<57:25,  2.86it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 144/10000 [00:50<57:27,  2.86it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 145/10000 [00:51<58:00,  2.83it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 146/10000 [00:51<58:02,  2.83it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 147/10000 [00:52<57:48,  2.84it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 148/10000 [00:52<57:38,  2.85it/s]

tensor([75, 67], device='cuda:7')


  1%|▏         | 149/10000 [00:52<57:31,  2.85it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 150/10000 [00:53<57:33,  2.85it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 151/10000 [00:53<57:36,  2.85it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 152/10000 [00:53<57:25,  2.86it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 153/10000 [00:54<57:36,  2.85it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 154/10000 [00:54<57:38,  2.85it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 155/10000 [00:54<57:28,  2.85it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 156/10000 [00:55<57:24,  2.86it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 157/10000 [00:55<57:17,  2.86it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 158/10000 [00:55<57:51,  2.84it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 159/10000 [00:56<57:45,  2.84it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 160/10000 [00:56<57:43,  2.84it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 161/10000 [00:56<57:44,  2.84it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 162/10000 [00:57<57:41,  2.84it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 163/10000 [00:57<57:51,  2.83it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 164/10000 [00:57<58:11,  2.82it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 165/10000 [00:58<58:07,  2.82it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 166/10000 [00:58<58:03,  2.82it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 167/10000 [00:59<57:49,  2.83it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 168/10000 [00:59<57:45,  2.84it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 169/10000 [00:59<57:46,  2.84it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 170/10000 [01:00<57:49,  2.83it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 171/10000 [01:00<58:09,  2.82it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 172/10000 [01:00<58:03,  2.82it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 173/10000 [01:01<58:01,  2.82it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 174/10000 [01:01<58:00,  2.82it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 175/10000 [01:01<57:55,  2.83it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 176/10000 [01:02<57:50,  2.83it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 177/10000 [01:02<57:59,  2.82it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 178/10000 [01:02<57:53,  2.83it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 179/10000 [01:03<57:47,  2.83it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 180/10000 [01:03<57:43,  2.84it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 181/10000 [01:03<57:27,  2.85it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 182/10000 [01:04<57:24,  2.85it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 183/10000 [01:04<58:14,  2.81it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 184/10000 [01:05<1:05:04,  2.51it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 185/10000 [01:05<1:09:09,  2.37it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 186/10000 [01:06<1:13:08,  2.24it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 187/10000 [01:06<1:11:59,  2.27it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 188/10000 [01:06<1:07:27,  2.42it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 189/10000 [01:07<1:04:26,  2.54it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 190/10000 [01:07<1:01:58,  2.64it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 191/10000 [01:08<1:00:52,  2.69it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 192/10000 [01:08<59:40,  2.74it/s]  

tensor([75, 67], device='cuda:7')


  2%|▏         | 193/10000 [01:08<58:59,  2.77it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 194/10000 [01:09<58:33,  2.79it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 195/10000 [01:09<58:26,  2.80it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 196/10000 [01:09<58:01,  2.82it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 197/10000 [01:10<57:58,  2.82it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 198/10000 [01:10<57:42,  2.83it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 199/10000 [01:10<57:35,  2.84it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 200/10000 [01:11<57:27,  2.84it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 201/10000 [01:11<57:18,  2.85it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 202/10000 [01:11<57:25,  2.84it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 203/10000 [01:12<57:30,  2.84it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 204/10000 [01:12<57:25,  2.84it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 205/10000 [01:12<57:27,  2.84it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 206/10000 [01:13<57:30,  2.84it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 207/10000 [01:13<57:36,  2.83it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 208/10000 [01:13<57:52,  2.82it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 209/10000 [01:14<57:44,  2.83it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 210/10000 [01:14<57:32,  2.84it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 211/10000 [01:15<57:36,  2.83it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 212/10000 [01:15<57:44,  2.83it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 213/10000 [01:15<57:51,  2.82it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 214/10000 [01:16<59:53,  2.72it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 215/10000 [01:16<59:00,  2.76it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 216/10000 [01:16<58:10,  2.80it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 217/10000 [01:17<57:29,  2.84it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 218/10000 [01:17<56:54,  2.86it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 219/10000 [01:17<56:38,  2.88it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 220/10000 [01:18<56:39,  2.88it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 221/10000 [01:18<57:10,  2.85it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 222/10000 [01:18<57:08,  2.85it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 223/10000 [01:19<56:45,  2.87it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 224/10000 [01:19<56:29,  2.88it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 225/10000 [01:19<56:20,  2.89it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 226/10000 [01:20<56:18,  2.89it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 227/10000 [01:20<56:47,  2.87it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 228/10000 [01:21<56:37,  2.88it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 229/10000 [01:21<56:24,  2.89it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 230/10000 [01:21<56:12,  2.90it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 231/10000 [01:22<56:05,  2.90it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 232/10000 [01:22<56:01,  2.91it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 233/10000 [01:22<56:11,  2.90it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 234/10000 [01:23<56:36,  2.88it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 235/10000 [01:23<56:27,  2.88it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 236/10000 [01:23<56:16,  2.89it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 237/10000 [01:24<56:15,  2.89it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 238/10000 [01:24<56:02,  2.90it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 239/10000 [01:24<55:53,  2.91it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 240/10000 [01:25<56:26,  2.88it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 241/10000 [01:25<56:21,  2.89it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 242/10000 [01:25<56:08,  2.90it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 243/10000 [01:26<56:05,  2.90it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 244/10000 [01:26<56:05,  2.90it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 245/10000 [01:26<56:12,  2.89it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 246/10000 [01:27<56:22,  2.88it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 247/10000 [01:27<56:38,  2.87it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 248/10000 [01:27<56:30,  2.88it/s]

tensor([75, 67], device='cuda:7')


  2%|▏         | 249/10000 [01:28<56:17,  2.89it/s]

tensor([75, 67], device='cuda:7')


  2%|▎         | 250/10000 [01:28<56:10,  2.89it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 251/10000 [01:28<55:56,  2.90it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 252/10000 [01:29<56:00,  2.90it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 253/10000 [01:29<56:19,  2.88it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 254/10000 [01:29<56:14,  2.89it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 255/10000 [01:30<56:06,  2.90it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 256/10000 [01:30<55:57,  2.90it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 257/10000 [01:31<55:43,  2.91it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 258/10000 [01:31<55:50,  2.91it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 259/10000 [01:31<56:01,  2.90it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 260/10000 [01:32<56:09,  2.89it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 261/10000 [01:32<56:13,  2.89it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 262/10000 [01:32<56:20,  2.88it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 263/10000 [01:33<56:07,  2.89it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 264/10000 [01:33<56:02,  2.90it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 265/10000 [01:33<56:02,  2.90it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 266/10000 [01:34<56:21,  2.88it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 267/10000 [01:34<56:25,  2.87it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 268/10000 [01:34<56:21,  2.88it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 269/10000 [01:35<56:10,  2.89it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 270/10000 [01:35<56:10,  2.89it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 271/10000 [01:35<55:57,  2.90it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 272/10000 [01:36<56:12,  2.88it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 273/10000 [01:36<56:16,  2.88it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 274/10000 [01:36<56:14,  2.88it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 275/10000 [01:37<56:07,  2.89it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 276/10000 [01:37<56:08,  2.89it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 277/10000 [01:37<55:50,  2.90it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 278/10000 [01:38<55:52,  2.90it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 279/10000 [01:38<56:30,  2.87it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 280/10000 [01:39<56:27,  2.87it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 281/10000 [01:39<56:16,  2.88it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 282/10000 [01:39<56:19,  2.88it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 283/10000 [01:40<55:59,  2.89it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 284/10000 [01:40<56:05,  2.89it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 285/10000 [01:40<56:26,  2.87it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 286/10000 [01:41<56:25,  2.87it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 287/10000 [01:41<56:04,  2.89it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 288/10000 [01:41<55:55,  2.89it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 289/10000 [01:42<55:36,  2.91it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 290/10000 [01:42<55:35,  2.91it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 291/10000 [01:42<55:42,  2.90it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 292/10000 [01:43<55:50,  2.90it/s]

tensor([75, 67], device='cuda:7')


  3%|▎         | 293/10000 [01:43<55:53,  2.89it/s]